# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  # disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Giới thiệu', path: 'menu', url: 'about.html'}
# - {name: 'Thông tin', path: 'menu', url: 'writing.html'}
- {name: 'Liên hệ', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'github', link: 'https://www.github.com/lenpaul'}
- {icon: 'twitter', link: 'https://twitter.com/hocbongdoidonglong'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:lienhe@doidonglong.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Mới hơn'
  previous_page: 'Cũ hơn'

sharing_button_prompt: 'Chia sẻ cho gia đình và bạn bè!'

related_posts: 'Bạn có thể quan tâm:'

post_date_prefix: 'Đăng ngày'
